name: Replace line in main.py

on:
  push:
    branches:
      - main
      - dev

jobs:
  replace-line:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Replace line in main.py
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          sed -i 's/run(host=\x27localhost\x27, port=8080, debug=True)/run(host=\x270.0.0.0\x27, port=80)/' main.py
        elif [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          sed -i 's/run(host=\x270.0.0.0\x27, port=80)/run(host=\x27localhost\x27, port=8080, debug=True)/' main.py
        fi

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
        git commit -am "Replace line in main.py"
        git push
